### ISSUE TITLE
How to setup vscode with `/*html*/` and typings

### ISSUE THREAD

**Issue by lmtr0** [slimjs/slim.js#116]
Hello there, good day!

How do I set up vscode for it to work with `/*html*/` and how do I set up typing with typescript?

this is how my vscode looks right now 
![image](https://user-images.githubusercontent.com/57605930/159790760-4df79687-6c4d-469f-8731-73a4f1ea54d2.png)

**Comment by eavichay** [comment]
This might work for you.

https://marketplace.visualstudio.com/items?itemName=Tobermory.es6-string-html

**Comment by lmtr0** [comment]
thank you
