### ISSUE TITLE
What is the point of this library?

### ISSUE THREAD

**Issue by eldoy** [slimjs/slim.js#127]
You know you can create components using just Javascript functions, right? And that such components are isomorphic and also works server side? With literally zero (0) kb package size or extra libraries needed?

```js
function myComponent(props) {
  return `<my-component>${props.name}</my-component>`
}
```

**Comment by eavichay** [comment]
Yes, you can also use React, Angular or Vue, or svelte. The point is that this is a stateful web-components library with in-template javascript.

Compared to other common libraries, it is fast and uses less computation power.

SSR is a real good solution if you are willing to pay the price for the servers, depends on the use case.
