### ISSUE TITLE
registerElement causes conflict with current webcomponents-lite.js polyfill in Firefox

### ISSUE THREAD

**Issue by mandymozart** [slimjs/slim.js#18]
I found the use of deprecated **document.registerElement()** caused slim.min.js to throw an error in the following function. 

I fixed the issue by uncommenting the new **window.customElements.define()**.

Is there a specific reason why this is uncommented in the first place? Thank you very much.

``` 
    /**
     * Declares a slim component
     *
     * @param {String} tag html tag name
     * @param {String|class|function} clazzOrTemplate the template string or the class itself
     * @param {class|function} clazz if not given as second argument, mandatory after the template
     */
    static tag(tag, clazzOrTemplate, clazz) {
        if (clazz === undefined) {
            clazz = clazzOrTemplate;
        } else {
            Slim.__templateDict[tag] = clazzOrTemplate;
        }
        Slim.__prototypeDict[tag] = clazz;
        window.customElements.define(tag, clazz);
        // document.registerElement(tag, clazz);
    }
```

**Comment by eavichay** [comment]
see issue #16

**Comment by mandymozart** [comment]
@eavichay excellent, glad to know its fixed. This is supposingly in the current release in npm?

**Comment by snuggs** [comment]
@eavichay @porschuetz missed a little cleanup in the process.

https://github.com/eavichay/slim.js/pull/20

**Comment by eavichay** [comment]
2.9.10 released
