### ISSUE TITLE
How to do constructor injection?

### ISSUE THREAD

**Issue by mandymozart** [slimjs/slim.js#19]
I want to do custom templates through a by overwriting the template getter.
And I want to inject an EventManager (potentially I will inject other things as well)

I get a Illegal constructor TypeError if I do that. 

**example.ts**
```
import { Slim } from "slim-js";
import { tag, useShadow, template } from "slim-js/Decorators";
import { TemplateProvider } from './../../utilities/templates'
import { EventManager} from './../../utilities/events'

@tag('sws-example')
@useShadow(false)
export class ExampleComponent extends Slim {

    public events: EventManager

    name: string;
    
    items: any[]
    
    public onBeforeCreated(): void {
        this.name = "example";
        this.items = [
            {name: 'Apple', id: 1},
            {name: 'Orange', id: 2},
            {name: 'Banana', id: 3}
        ];
    }

    public selectItem(event: Event): void {
        // invoked!
        let itemId = $(event.target).attr('id');
        alert('Selected item '+itemId);
    }
    
}

@tag('sws-item')
@useShadow(true)
@template(`
<button><slim-content></slim-content></button>
`)
export class ChildComponent extends Slim {

}

```

and in main.ts I create the component like this: 
```
import { template } from 'slim-js/Decorators'
...


        template(templateProvider.templates['sws-example'])(ExampleComponent)
        let eC = new ExampleComponent()
// Setter injection trying alternatives
        eC.events = events
```

This error message I still get:
```
Slim.min.js:1 Uncaught TypeError: Illegal constructor
    at ExampleComponent._CustomElement (Slim.min.js:1)
    at ExampleComponent.Slim (Slim.min.js:1)
    at new ExampleComponent (example.ts:8)
    at main.ts:25
    at HTMLDocument.<anonymous> (zepto.js:446)
```

Is there any way to achieve something like this? 

Thank you very much,

Tilman

**Comment by eavichay** [comment]
the Example component's prototype will have a template getter that returns null.
Try in your main.ts doing this:

```js
template(templateProvider.templates['sws-example'])
class SomeNewElementClass extends ExampleComponent {}

let eC = new SomeNewElementClass()
```


can you put your code in webpackbin or similar?

**Comment by mandymozart** [comment]
I did put together a sandbox in webpackbin

https://www.webpackbin.com/bins/-KpPuTpl9q-E_E6KSmBr

And we here at the office wanted to ask you, if there is a specific reason why you emit "Illegal constructor TypeError" and do not allow injections? Or is there a possible fork that we can provide to the issue?

With very kind regards and thanks for you help
tilman

**Comment by eavichay** [comment]
for some reason i cannot edit or view any of the files in your bin

**Comment by eavichay** [comment]
basically, custom elements should not have arguments in their constructors, as they are created from the HTML. slim provides an injection mechanism (currently not yet documented) that is invoked between the "onBeforeCreated" and "onCreated". example:

```html
<my-element some-property="{injectionName}"></my-element>
```

and in your source code best used before the HTML is created

```js
let SomeSingleton = new MySingleton();

Slim.inject('injectionName', (element) => {
  //element is optional
  return SomeSingleton;
})

...

@tag('my-element')
class extends Slim {
  onCreated() {
    console.log(this.someProperty); // Injection!
  }
}
```

if The injection is declared before <my-element> (or any other element using the injection) then you will have access to the injection result at the designated property

**Comment by mandymozart** [comment]
you just have to click on **Copy Bin** in the left sidebar than you can edit you own derivative.

**Comment by eavichay** [comment]
I'm not sure what you are trying to achieve. If you want to use arbitrary templates, wrap them in template tag and not use existing declared custom element tag

...

do you wish to inject your template during runtime from template provider?

**Comment by mandymozart** [comment]
yes, that was the idea. We are building an app that is unfortunately strongly backend rendering based and I have to avoid duplicate dom at runtime at a minimum. I found a way around within our workflow.

**Comment by eavichay** [comment]
1. use injections <my-tag template-provider="{myTemplateProvider}" ...>
2. before the element is created, declare the injection Slim.inject('myTemplateProvider', () => templateProviderInstance)
3. on the class itself, declare a template getter.... class MyClass { get template() { return this.myTemplateProvider.getTemplate() } }

during the creation routine the injection will take place, during the rendering phase it will take the template string from the provider

for that tag, don't use the template decorator

**Comment by eavichay** [comment]
Please let me know if that works for you and we can close this thread

**Comment by mandymozart** [comment]
hey Avichay, due to the many issues I had trying to implement with your library I had to drop it for the current project. But I understand how difficult it is to concentrate on certain features of a library.

**Comment by eavichay** [comment]
:( what was the problematic feature that made you drop it?
