### ISSUE TITLE
Recursive Repeaters

### ISSUE THREAD

**Issue by mandymozart** [slimjs/slim.js#21]
I understood right, recursive repeaters are not possible?
this is the use case.
```
@tag('sws-navigation-item')
@useShadow(true)
@template(`
<ul>
    <li slim-repeat="items" slim-repeat-as="item">
        <a bind href="[[item.url]]">[[item.title.text]]</a>
        <sws-navigation-item interactive item="[[item.childLayer]]" click="openItem" id="[[item.id]]"></sws-navigation-item>
    </li>
</ul>
`)
export class NavigationItem extends Slim {}
```

**Comment by eavichay** [comment]
nested repeaters should work, could you upload a code with the problem?

in your example, your are recursively repeating the same element into itself, which may get into an endless loop.

**Comment by eavichay** [comment]
interesting question. Never tested, but make sure your data isn’t repeating endlessly

**Comment by eavichay** [comment]
have you considered wrapping the <sws-navigation-item> (in the template) with a div using slim-if="item.childLayer" ?

**Comment by mandymozart** [comment]
https://www.webpackbin.com/bins/-KpogSA1DfBiTEvX04CO

Yes, I did, and my data tree is not endless. (see the console. it parses a mock data tree)

works like a charm. =) thanks. 
![screen shot 2017-07-24 at 15 45 27](https://user-images.githubusercontent.com/1228101/28526104-c8a05c00-7086-11e7-8b11-3553c9b6043d.png)


Update: It actually ignored the 3rd layer already. . it doesn't recurse. I have overseen this yesterday.
