### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by linvi** [slimjs/slim.js#35]
Hello,

I wanted to know if slim.js supports server side rendering. I have been looking at the documentation to see if this feature was available but I could not find any mention of it.

Thank you for your help and good job.

Linvi

**Comment by eavichay** [comment]
@linvi 
Hi. Web Components are a client-side only technology. It is based on native DOM API (which only runs in the browser). The whole point of using web components and custom elements is to extend the primitive elements exists on the browser (i.e. span, div, etc.) and create new ones with code-behind and logic.

You could generate code in the server and load only the components in use.

If you could please specify how your servers works and what are the requirements I could point out how to make it work with custom elements / web components.

slim.js is an extension of the native API that provides essentials that does not exists (and probably never will) on the browser: Data binding, Plugins, Extensions - to the native API.

10x.

**Comment by linvi** [comment]
Hello,

I am aware that web components are based on browser rendering but I was just wondering how to render web components for robots that unlike google do not execute javascript.

I am planning on using node in the backend to execute the javascript necessary by the web component.

Your input would be greatly appreciated.

Thanks,
Linvi

**Comment by eavichay** [comment]
You can use aria-* attributes that helps robots understand what is going on the website.
Robots (as google says) can read web-components. They do not care about div vs. span but they do care about metadata and aria-* attributes.

**Comment by linvi** [comment]
Thank you for the feedback, I will read more about the subject.

Cheers,
Linvi
