### ISSUE TITLE
Support shadyCSS

### ISSUE THREAD

**Issue by David-Mulder** [slimjs/slim.js#39]
Style encapsulation seems to be an important part missing in slim.js . Considering the "slim" nature I think it's good to leave it out by default, but an optional decorator allowing one to use it would be amazing.

It's fairly easy to 'trick' shadyCSS with

    const templateEl = document.createElement('template');
    templateEl.innerHTML = templateContent;

etc.

**Comment by eavichay** [comment]
Please elaborate, or show code samples?

**Comment by David-Mulder** [comment]
Duplicate of #34, just didn't know that issue existed when I wrote this.
