### ISSUE TITLE
@attribute throws 'cannot read property push of autoBoundAttributes'

### ISSUE THREAD

**Issue by David-Mulder** [slimjs/slim.js#41]
![image](https://user-images.githubusercontent.com/46602/38028751-1ed8de38-3294-11e8-9dc6-04d90e27485d.png)

This is in combination with Webpack and Babel, using the following code

    @tag('some-element')
    class A extends Slim {
      @attribute
      myProperty // bounds to my-property attribute automatically.
    }

**Comment by eavichay** [comment]
10x

**Comment by David-Mulder** [comment]
?

**Comment by eavichay** [comment]
Need to add a default value to the decorator, something like `... target.constructor.autoBoundAttributes = target.constructor.autoBoundAttributes || []` before pushing it.
Would you like to contribute or want me to do it myself?

**Comment by eavichay** [comment]
@David-Mulder Using polyfills, property attribute cannot target the correct class, as the actual HTML element's class is not the one provided by the code. I will try to look up some way to workaround this, but for now, this attribute remains undocumented as it doesn't work properly.

**Comment by eavichay** [comment]
Deprecated Feature on deprecated version.
