### ISSUE TITLE
Binding system + loop behaves oddly (errors in chrome and ignored in Firefox)

### ISSUE THREAD

**Issue by David-Mulder** [slimjs/slim.js#44]
Given

    this.tests = ['a', 'b', 'c'];        
    setTimeout(() => {
        this.tests = ['d', 'e'];
    }, 1000);

and

        <div s:repeat="tests as test" bind>
            {{test}}
        </div>

it will show in Firefox:

> a
> b
> c

in Chrome:

> d
> b

\+ 

![image](https://user-images.githubusercontent.com/46602/38079850-32c41384-3340-11e8-89a7-0f88768578b4.png)

**Comment by David-Mulder** [comment]
<div s:repeat="tests as test" class="wecoma-consent-bar-purpose">
        <span bind>{{test}}</span>
    </div>

Fixes the error in chrome, but does not fix the Firefox problem. And just FYI, the `Slim.qSelectAll` returned a `br` for some unknown reason.

**Comment by David-Mulder** [comment]
And somehow looked totally over the fact that Firefox is throwing a

> TypeError: binding.destroy is not a function

error on line 234.

**Comment by eavichay** [comment]
fixed in 3.2.7
🍾
