### ISSUE TITLE
`ev.target` doesn't have repeater bindings bound in Firefox

### ISSUE THREAD

**Issue by David-Mulder** [slimjs/slim.js#45]
In Firefox I need to do 

    const purpose = ev.target['_slim_internals_'].repeater.purpose;

to access something from the repeater scope, whilst in Chrome I can do

    const purpose = ev.target.purpose

**Comment by eavichay** [comment]
Please add the full code so I could reproduce, please.
The current problem is that there are two different repeater mechanism: one for chrome/safari and the second for the other browsers. The polyfills do mimic the behavior but reacting to mutation observer is different than how the browser natively supports custom elements.

Repeating elements (even nesting) seems to work (check the documentation website, written in slim.js), so I encourage you to share the code for proper reproduction.

**Comment by eavichay** [comment]
I would like to know in what part of the lifecycle you are trying to fetch the data.

**Comment by eavichay** [comment]
Fixed on 3.2.7
