### ISSUE TITLE
ES6 version with good export

### ISSUE THREAD

**Issue by vogloblinsky** [slimjs/slim.js#46]
Is it possible to change the Slim.es6.js file ?
You are using an UMD module inside Slim.js
It could be better to export directly Slim class in Slim.es6.js, and add your UMD stuff during ES5 build.

**Comment by eavichay** [comment]
Basically, if you choose to work with webpack or other bundlers, you may want to import the default Slim.js file. The export is done manually in the src/Slim.js file. You are welcome to PR and add other export options.
👍

**Comment by vogloblinsky** [comment]
sorry i forgot to say that it is for using it directly inside a js file, inside an ES6 module in the browser.
i mean with type="module"
i will push the PR asap

**Comment by eavichay** [comment]
That would be awesome. Thanks

**Comment by eavichay** [comment]
@vogloblinsky When could I expect your PR?

**Comment by eavichay** [comment]
Fixed in version 4

**Comment by vogloblinsky** [comment]
Thanks
