### ISSUE TITLE
Content transclusion

### ISSUE THREAD

**Issue by DaSchTour** [slimjs/slim.js#47]
I'm not sure if this is a missing feature or just missing documentation. Is there any possibility to transclude the content inside a component into a slot inside the template or create a component without template that preserves the content inside?

**Comment by eavichay** [comment]
@DaSchTour Content transclusion is provided by default using shadow DOM and `<slot />` nodes. This is part of the native custom elements' [API](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot). If you believe transclusion should be a feature on non-shadow-DOM elements, this can be done using the plugins/extensions of Slim.

`Slim.customDirective`, or `Slim.plugin`.

Worth discussion, IMHO.
