### ISSUE TITLE
Props passed to computed binding in s:repeat has no args

### ISSUE THREAD

**Issue by hagen** [slimjs/slim.js#51]
Hi again,
trying to use computed bindings inside a `s:repeat`. See line `{{calcPercentage}}`
```js
@tag('custom-table')
@template(`
<div>
 <table>
    <tbody>
      <tr s:repeat="items as item">
        <th>
          <a click="navToEdit(item)" bind>{{item.name}}</a>
        </th>
        <td bind>{{item.status}}</td>
        <td bind>{{calcPercentage(item)}}%</td>
      </tr>
    </tbody>
  </table>
</div>`
export default class TableComponent extends Slim {
  items = []
  onBeforeCreated() {
    items = [
      { name: 'first', status: 'ok', num: 50 },
      { name: 'second', status: 'ok', num: 80 },
    ]
  }
  calcPercentage(item) {
    // item is 'undefined'
    return ( item.num / 100 ) * 100 // just an example of trying to access props in 'item'
  }
  ...
}
```

`calcPercentage` is not getting passed the `item` from s:repeat. `item` is `undefined` in the method. Why is `item` not passed to the function in the computed binding?

**Comment by eavichay** [comment]
Hey. Thanks for the issue, please try using a non-primitive tag, such as `@tag('some-component')` as you cannot use native HTML elements.
Please update if that works for you.

**Comment by eavichay** [comment]
also, try `onBeforeCreated` and not `onBeforeCreate`

You can also try initialising your data in the constructor function.

**Comment by hagen** [comment]
Those were typos sorry - all component names do not clash with standard HTML tags, and I use `onBeforeCreated`.
I moved the `item` initialisation to `constructor()`, but still the first arg in the computed binding function is `undefined`.
Here's a sample of the output:
![image](https://user-images.githubusercontent.com/5161952/42419567-10214d64-82fb-11e8-8ea9-d6e9db91c34f.png)

Two of the columns are bound correctly, but to regular props of each `items` entry. The computed column just shows the string `functionName(item)`. 

Here's the _actual_ html I'm using in the @template decorator:
```html
<table>
  <tbody>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Completion rate</th>
    </tr>
    <tr s:repeat="items as item">
      <th>
        <a click="navToEdit(item)" bind>{{item.name}}</a>
      </th>
      <td bind>{{item.status}}</td>
      <td bind>{{calcPercentage(item)}}</td>
    </tr>
  </tbody>
</table>
```

Debugging, the passed in item is undefined, despite being assigned in the `s:repeat="items as item"` Slim binding attribute.

![image](https://user-images.githubusercontent.com/5161952/42419594-9d4c06fc-82fb-11e8-8473-0532e9c75f20.png)

**Comment by eavichay** [comment]
Please upgrade to 3.3.1, just uploaded a fix.

Nice catch! 👍

**Comment by eavichay** [comment]
btw - no need for "bind" attribute for text-binds since 3.3.0

**Comment by hagen** [comment]
Thank you!

**Comment by eavichay** [comment]
@hagen Works for you now?

**Comment by hagen** [comment]
@eavichay works since upgrading, thanks
