### ISSUE TITLE
Incorrect call to autoBoundAttributes.includes inside attributeChangedCallback prevents attribute-property syncing

### ISSUE THREAD

**Issue by yavuztor** [slimjs/slim.js#52]
When an attribute is set using `element.setAttribute(..)`, its auto-bound property is not updated properly, due to an incorrect call for `autoBoundProperties.includes`. https://github.com/slimjs/slim.js/blob/282ba0268fb663c607e81eab3fc6c9e08f62409d/src/Slim.js#L343

Since `includes` is a function, `this.autoBoundAttributes.includes[attr]` should be `this.autoBoundAttributes.includes(attr)`

**Comment by eavichay** [comment]
great catch!
Would you pr?

**Comment by yavuztor** [comment]
Sure. I will get that soon.
