### ISSUE TITLE
Evaluate bindings in shadow dom

### ISSUE THREAD

**Issue by ThatScalaGuy** [slimjs/slim.js#56]
Hi, 
I am wondering if it is possible to evaluate the bindings when using a shadow dom. 

The attached fiddle shows what I want to achieve. 

http://jsfiddle.net/wmoL2v81/13/

Or is this not possible with slim.js

**Comment by eavichay** [comment]
Basically, it is possible, adding a slim [plugin](https://github.com/slimjs/slim.js/wiki/Attaching-functional-plugins).

Something like 
```js
Slim.plugin('create', (element) => {
  const children = Array.from(element.children);
  requestAnimationFrame( () => {
  element._bindChildren(children);
  element.commit();
  });
});
```

If you want to restrict for specific elements, in the plugin function filter the elements by their localName... `if (element.localName === 'my-custom-tag') ... `

Will that work for you?

**Comment by eavichay** [comment]
https://jsfiddle.net/wmoL2v81/25/

**Comment by ThatScalaGuy** [comment]
Did not see your replay. I will check your recommendation next week. Thx so far.
