### ISSUE TITLE
update docs for webcomponentsjs polyfill v2

### ISSUE THREAD

**Issue by btopro** [slimjs/slim.js#64]
`<script src="node_modules/@webcomponents/webcomponentsjs/webcomponents-bundle.js"></script>`
is the new way to do it in V2 spec, talks ref 1.x

**Comment by eavichay** [comment]
Thanks. Now that Safari supports web components without the need for polyfills, and firefox's next release will support web-components the polyfills are required only for IE11 or Edge.

Should I add this into the README or the docs?

WDYT?

**Comment by btopro** [comment]
definitely. here's the language and stats I use in our wcfactory readme -- https://github.com/elmsln/wcfactory#end-user-support

fyi, SlimJS is a supported library in wcfactory so if there are things you'd like to see changed in our boilerplate to better promote your library's preferred starting point please feel free to post / issue PRs. I used the doc site to make the boilerplate but always open to tweak.

**Comment by eavichay** [comment]
Your tool looks awesome.
I'm on it 👍

**Comment by btopro** [comment]
https://youtu.be/CMNYuXTe1tM?t=34m46s - Slim JS discussed in the tooling / CLI.
https://github.com/elmsln/wcfactory/tree/master/packages/generator-wcfactory/generators/init/wcfTemplates/libraries/Slim - slim template / package.json that gets pulled from to make new elements
