### ISSUE TITLE
Changes between 3xx and 4xx

### ISSUE THREAD

**Issue by btopro** [slimjs/slim.js#65]
Is there a list of changes / are they completely in switching to typescript or are there API changes as well? I got a ding from resolve bot about new version existing but I don't see anything mentioned about it here as far as release notes.

Thanks

**Comment by eavichay** [comment]
The only breaking change is that the directives have been extracted into different files, i.e. you need to import them (or add link-href in your html).
There are two versions for each file: the es6 native modules and the no-module fallback.

```html
<script src="..../Slim.js" type="module"></script>
<script src=".../Slim.nomodule.js">
```

Using webpack should make no difference, just use `import { Slim } from 'slim-js'` as usual.

If you are about to use the s:repeat, s:if, s:switch... you need to require these also.
There is a "load-all" directive. `import 'slim-js/directives/all.js'`

For all the directives there is also a .nomodule.js fallback file.

The difference between nomodule and "regular" files are that nomodule ones does not provide export.

Nothing is written in typescript, but there is a d.ts file for your convenience.

**Comment by eavichay** [comment]
I have just updated the README. Thanks.
