### ISSUE TITLE
Repeat directives nested

### ISSUE THREAD

**Issue by vogloblinsky** [slimjs/slim.js#70]
Hi,

Considering this array :

```
let list = [[1], [1,1], [1,2,1]]
```

How can i iterate to the elements ?

```
<div s:repeat="list as line">
    <triangle-item s:repeat="line as item" text="{{item}}"></triangle-item>
</div>
```

I correctly got the first list rendered, but inside each first line, i got `<!--triangle-item s:repeat="line as item"-->`

Thanks

**Comment by eavichay** [comment]
Found a workaround: https://jsfiddle.net/cx1h9jpL
Replace the div with your own custom element and nest the repeat inside.

Converting this to a feature request.

**Comment by vogloblinsky** [comment]
Thanks
This is for this benchmark : https://github.com/vogloblinsky/web-components-benchmark
The pascal triangle implementation.
I will update it tonight
