### ISSUE TITLE
Add slim.js to Benchmark

### ISSUE THREAD

**Issue by vogloblinsky** [slimjs/slim.js#71]
Hi,

I have created a benchmark suite for Web Components librairies. slim.js is implemented, and you can see the raw results here : vogloblinsky.github.io/web-components-benchmark

I will release soon a blog post explaining in detail that, but i want a feedback of many librairies authors before, to be sure i am not wrong in my implementations.

Source code here : vogloblinsky/web-components-benchmark

Can you have a look and give me some feedbacks ?

Thanks

**Comment by eavichay** [comment]
10x. Looks interesting. I do question myself if pascal triangle and todo-list is a use-case to be considered?

Most benchmarks are focusing on repeating elements with minor manipulations. I was thinking of another approach of a benchmark: A real-world app that the benchmarks are:
Loading/Parsing/Interactivity, etc.
__Source code__ size, not just the bundle. The source should be clean, simple and easy to read.
Dependencies list
Memory Leaks / Avg. memory consumption during scenarios
FPS for animations.
Community's opinions about using the libraries.

I guess the app should be something like a trello-like board + document (markdown) editor + possibly comments / chat section. I was inspired by the "real-world-app" project which the focus was on showcasing the code. I believe that if you try to measure performance in these all-looks-the-same apps that comply to the real world (i.e. NOT 10K ITEMS in a list) the differences are so minor they sometimes cannot be detected.

The app should also be measured in a web-view of a mobile device and mobile browser.

Focus on __code readability__, loading/parsing, dependency hell and tooling complexity are major key points when we decide the next stack to rely on for the next project.

WDYT?

**Comment by vogloblinsky** [comment]
I understand your feedback.
I will add a third implementation like you suggested : https://github.com/gothinkster/realworld can be an option but very simple; or https://hnpwa.com/. 
I didn't know others projects with many different code implementations.

**Comment by eavichay** [comment]
Already part of the real-world project
