### ISSUE TITLE
appreciate your feedback for custom element reactions diagram

### ISSUE THREAD

**Issue by AndyOGo** [slimjs/slim.js#74]
I just released an adapted version of the interactive react lifecycle methods diagram for custom element reactions:
https://andyogo.github.io/custom-element-reactions-diagram/

If you have time, I would appreciate your feedback very much.

**Comment by eavichay** [comment]
Look's good. I would split the constructor part into two cases: When an element is created by using some innerHTML of a wrapping element: the custom-element will have children, and when using it with `document.createElement('my-elem')` or `new MyElement()` which does not allow to populate anything (including attributes)

**Comment by AndyOGo** [comment]
Fixed with:
https://github.com/AndyOGo/custom-element-reactions-diagram/pull/19

And published
