### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by gabriel-fallen** [slimjs/slim.js#76]
It would be very helpful if documentation (at [main site](slimjs.com)) contained a link to [Slim Webpack Biolerplate](github.com/slimjs/slim-webpack-boilerplate/) project.

Also, Web Components polyfill at the Getting Started page references version `1.0.17` of `webcomponents-lite.js`, and the Boilerplate project references version `1.2.7`, while the last version is `1.3.3`. Does it make sense to update to this version?

**Comment by eavichay** [comment]
Regarding the boilerplate: It's still not finalised so I'm waiting a little bit until it is ready.

Regarding the polyfills: All evergreen browsers now supports web components (no need for polyfills). I think they should be mentioned as a link to some external site describing when to use it.

You can easily PR to the docs [repo](https://github.com/eavichay/slimjs-docs)

👍

**Comment by gabriel-fallen** [comment]
> You can easily PR to the docs [repo](https://github.com/eavichay/slimjs-docs)

Which reminds me: you should put this link on the docs site too! Because I was looking for it but couldn't find... :)

> Regarding the polyfills

Yeah, later I found the discussion in #64 

> Regarding the boilerplate

It was very useful and even enabling for me as I copied Webpack and Babel config from it, and without it nothing worked. I'm not good at Webpack config and Parcel doesn't work for my experiment at all.

**Comment by eavichay** [comment]
Parcel doesnt work with web components without hassle and a polyfill which called `web-components-loader` which actually executes in the runtime and alters the way webpack transpiles classes creation. I started a discussion in parcel's repo and their opinion is "zero-configuration" which means it simply cannot be done without hassle. IMO parcel is not a real-world solution.

**Comment by eavichay** [comment]
![screenshot](https://user-images.githubusercontent.com/1084459/53342498-ba597780-3916-11e9-9212-8151d24d888c.png)
You can see on the top right - issues for documentation :)

**Comment by gabriel-fallen** [comment]
> You can see on the top right - issues for documentation

I guess the red badge in the bottom right corner attracted all my attention. :smile: 

All right then, we can close this issue I guess.
