### ISSUE TITLE
Storybook components

### ISSUE THREAD

**Issue by kaesar** [slimjs/slim.js#79]
Hi, I was wondering if `slimjs` could consider components with [Storybook](https://storybook.js.org/) or simply is possible with `Storybook for HTML` (storybook allow reuse components in development time with elegant UI and drag and drop).
I think `slimjs` proposal is great. I can imagine mixed with `Storybook` would be so cool.
Thanks any way.

**Comment by eavichay** [comment]
@kaesar, you may want to check showroom.js - It is a dedicated "storybook"-like tool for web components + full puppeteer integration out of the box.

We use it at production.

Integration with storybook is just like any other storybook-custom-elements integration.

**Comment by kaesar** [comment]
Ok, I'll take a look at it. Thanks.
