### ISSUE TITLE
WEBP Support

### ISSUE THREAD

**Issue by ysb** [slimjs/slim.js#88]
Can you add support for uploading .webp files. It's very popular on these days.

**Comment by eavichay** [comment]
Hey, could you explain further what are you looking for?

**Comment by ysb** [comment]
@eavichay Hi, i want to be able to upload webp files by slim. Because people are saving images from popular websites with webp extension and want to upload to our cms.

**Comment by ysb** [comment]
Oh, I'm sorry, it's wrong slim. Closing the issue.
