### ISSUE TITLE
s:if Conditional rendering not working

### ISSUE THREAD

**Issue by JamieVaughn** [slimjs/slim.js#90]
While using SlimJS for a project I need the s:if conditional rendering feature. I converted the example code to the no decorator syntax like so to test it out: 
```
Slim.tag("my-tag",
        '<div s:if={{myBoolean}}>Now you see me</div>' +
       '<div s:if={{!myBoolean}}>Now you do not!</div>',
       class MyTag extends Slim {
           onBeforeCreated() {
           this.myBoolean = true;
               setInterval(() => {
                   this.myBoolean = !this.myBoolean
               }, 500)
          }
     }
)
```

And found that both divs render immediately. So it seems like the conditional rendering feature is not working right now.

I'm importing slimJS this way:
```
<script type="module">
        import {Slim} from 'https://unpkg.com/slim-js@4.0.7/Slim.js';


</script>
```
And just putting the `<my-tag></my-tag>` element right into the body of index.html

Code repo in case it helps diagnosing: https://github.com/JamieVaughn/mtg/tree/master/slim

**Comment by eavichay** [comment]
Hey,
if / switch-case / repeat, are OPTIONAL, therefore if you require using them, you should import these also.
https://unpkg.com/slim-js@4.0.7//directives/if.js
https://unpkg.com/slim-js@4.0.7//directives/repeat.js
https://unpkg.com/slim-js@4.0.7/directives/switch-case.js

**Comment by eavichay** [comment]
Or use all of them at once
https://unpkg.com/browse/slim-js@4.0.7/directives/all.js

**Comment by eavichay** [comment]
Please let me know if that works, so I could close this issue.

**Comment by JamieVaughn** [comment]
Thank you for the tip! I am having trouble implementing it though in an es6 module script. I'm not sure the proper syntax for the directive import, since I couldn't find the export names for the directives. I tried this but that didn't seem to work:

```
<script type="module">
        import {Slim} from 'https://unpkg.com/slim-js@4.0.7/Slim.js';
        import 'https://unpkg.com/browse/slim-js@4.0.7/directives/all.js';

</script>

```

my other thought was to do something like `import { if, switch, repeat } from 'https://unpkg.com/browse/slim-js@4.0.7/directives/all.js'; ` But that didn't work either

**Comment by eavichay** [comment]
Remove the 'browse' from the URL.
```
import { Slim } from "https://unpkg.com/slim-js@4.0.7/Slim.js";
import "https://unpkg.com/slim-js@4.0.7/directives/if.js";
```

**Comment by eavichay** [comment]
FYI if you import slim from a  local node-module, you should also import the directives from the same module.

**Comment by JamieVaughn** [comment]
Oops, I should have caught that 'browse' thing... anyways that fixed it and it works now. Thanks vary much for the assistance and for a nice minimalist web-components library!

**Comment by eavichay** [comment]
You might want to try one of my two other libraries. There is an even lighter library @neow/web (alpha) it is much faster, fully expressional but lacks repeat directive (but you can add your own).

Also another one, ottavino is an object based one, that can "convert" regular HTML elements into custom-elements behavior.

https://github.com/neo-web/neow - https://webcomponents.dev/edit/fEa6HG5aeEwJ75vqDVyj
https://github.com/betterthancode/ottavino - https://webcomponents.dev/edit/RA7SjhwlA7S18lZy9kkL

I would appreciate your feedback.

**Comment by JamieVaughn** [comment]
Cool, both of those look really nice. I'll use them in the same project I'm doing that I used Slim for. and I let you know how it goes! Thanks!
