### ISSUE TITLE
[SUGGESTION] Provide a way to take outter css in the shadowDOM

### ISSUE THREAD

**Issue by naiteon** [slimjs/slim.js#92]
Hi! I'm considering using this lib in my project but I need to wrap up bootstrap classes and tags into reusable components.

I read this article (https://medium.com/lightbaseio/bootstrap-4-lit-element-37c857a6bcca) , where they show how to do this. The custom elements don't get any of bootstrap' style since they are in the shadow dom. But Lit Element provides an interface method to allow for rendering the shadow dom into the light dom (thus getting the outter style). The interface method is "createRenderRoot()". 

Here is the definition and logic behind it:
https://github.com/Polymer/lit-element/blob/master/src/lit-element.ts

Could you please take a look at that and see if it is feasible with Slim.js or at least taken into account for a next release?

Thank you in advance and keep up the good work!

**Comment by eavichay** [comment]
Hi.

Edited: Until constructible style-sheets will be fully implemented, this is a suggestion - based on *native* behavior of browsers.

Using the shadow root is NOT mandatory. You can visit the documentation website - http:slimjs.com and see the source maps.

If you still wish to use shadow root, I recommend either using internal style nodes with `@import` statements or sharing styles using a custom element for style-sharing.

Modulizing the parts you wish to import into your component improves performance, in case you choose to go with shadow DOMs.

Check out this implementation (taken from a production code) - modulizing css into blocks and sharing between shadow DOMs.

```typescript
const valueCache: Record<string, Promise<string>> = typeof (<any>window)['AppContext'] === 'object' ? (<any>window)['AppContext'].getConfig('styleCache') : {};

export class StyleLoader extends HTMLElement {
    connectedCallback () {
        const href = this.getAttribute('href');
        const name = this.getAttribute('name');

        if (!name || !href) {
            return;
        }
        if (valueCache[name] && typeof (<any>valueCache[name]).resolve === 'function') {
            const resolve = (<any>valueCache[name]).resolve;
            fetch(href)
                .then(r => r.text())
                .then(styleText => resolve(styleText.replace(/([\n|\r|\t])/gm, '')))
                .catch(() => {});
        }
        if (!valueCache[name]) {
            valueCache[name] = new Promise((resolve, reject) => {
                fetch(href).then(r => r.text()).then(styleText => resolve(styleText.replace(/([\n|\r|\t])/gm, ''))).catch(reject);
            });
        }
    }
}

export class SharedStyle extends HTMLStyleElement {
    public styleLoaded = false;
    constructor() {
        super();
        this.applyStyle();
    }

    connectedCallback() {
        this.applyStyle();
    }

    applyStyle() {
        if (this.styleLoaded) {
            return;
        }
        const name = this.getAttribute('name');
        if (name) {
            let p = valueCache[name];
            if (!p) {
                let resolve;
                p = new Promise<string>(res => resolve = res);
                (<any>p).resolve = resolve;
                valueCache[name] = p;
            }
            p.then(text => this.innerHTML = text);
            this.styleLoaded = true;
        }
    }
}

customElements.define('shared-style', SharedStyle, {extends: 'style'});
customElements.define('style-loader', StyleLoader);
```

the usage is simple:
in the main HTML
```html
<style-loader href="/path/to/buttons.css" name="buttons"></style-loader>
<style-loader href="/path/to/menus.css" name="menus"></style-loader>
```

in your shadow root (any component)
```html
<style is="shared-style" name="buttons"></style>
```

This implementation is performant, I'm using it on production on several projects, as long as you keep you CSS "blocks" separate correctly, it's super-fast.

**Comment by naiteon** [comment]
Thank you so much Avichay Eyal ! 

Mazel tov! It's a great library my friend

רודריגו
