### ISSUE TITLE
Non-minified package distribution

### ISSUE THREAD

**Issue by jbruni** [slimjs/slim.js#97]
@eavichay Hey, man! Thanks for your brilliant work!

Using Chrome Dev Tools, the `Slim` class appears as `u`

`u`?

I found that this is because, even though I'm using a stack with npm, vite, esbuild, rollup... the `import { Slim } from 'slim-js'` actually brings in the code from the minified `index.js` at `node_modules/slim-js/dist/index.js`

:scream: 

Could you please let the `src` folder intact in the package exports? So I can import from `slim-js/src` or, really, any other file on it?

From your README: 

```
 It also provides access to it's internals, if you want to hack things out.
```

This is great! If it can also provide the non-minified internals for us, mere mortals, it will become even greater!

Thank you very much. :bow:

**Comment by eavichay** [comment]
Done. https://github.com/slimjs/slim.js/commit/c04cc04968f1bd86fbaaf937b70f5d91dd1e809f
Published with 5.0.9
